<?php

use Drupal\entity_browser\Element\EntityBrowserElement;

/**
 * Implements hook_install().
 */
function test_10a21ffe_install() {
  entity_get_form_display('node', 'page', 'default')
    ->setComponent('field_hero_image', [
      'type' => 'entity_browser_file',
      'settings' => [
        'entity_browser' => 'image_browser',
        'field_widget_edit' => TRUE,
        'field_widget_remove' => TRUE,
        'view_mode' => 'default',
        'preview_image_style' => 'thumbnail',
        'open' => TRUE,
        'selection_mode' => EntityBrowserElement::SELECTION_MODE_APPEND,
      ],
      'region' => 'content',
    ])
    ->save();
}
