<?php

use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_install().
 */
function test_c74eadd0_install() {
  $display = entity_get_form_display('media', 'video', 'default');
  // Add field_image to the display and save it; lightning_media_image will
  // default it to the image browser widget.
  $display->setComponent('field_image', ['type' => 'image_image'])->save();
  // Then switch it to a standard image widget.
  $display
    ->setComponent('field_image', [
      'type' => 'image_image',
      'weight' => 4,
      'settings' => [
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ],
      'region' => 'content',
    ])
    ->save();
}

/**
 * Implements hook_uninstall().
 */
function test_c74eadd0_uninstall() {
  FieldConfig::loadByName('media', 'video', 'field_image')->delete();
  field_purge_batch(10);
}
