<?php

/**
 * @file
 * Contains install, uninstall, and update hooks for Lightning Media Audio.
 */

use Drupal\lightning_core\ConfigHelper as Config;

/**
 * Creates the media_library form display for audio files.
 */
function lightning_media_audio_update_8001() {
  Config::forModule('lightning_media_audio')
    ->optional()
    ->getEntity('entity_form_display', 'media.audio.media_library')
    ->save();
}
