<?php

use Drupal\entity_browser\Element\EntityBrowserElement;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_install().
 */
function test_2f72f4a4_install() {
  entity_get_form_display('node', 'page', 'default')
    ->setComponent('field_lightweight_image', [
      'type' => 'entity_browser_file',
      'settings' => [
        'entity_browser' => 'image_browser',
        'field_widget_edit' => TRUE,
        'field_widget_remove' => TRUE,
        'view_mode' => 'default',
        'preview_image_style' => 'thumbnail',
        'open' => TRUE,
        'selection_mode' => EntityBrowserElement::SELECTION_MODE_APPEND,
      ],
      'region' => 'content',
    ])
    ->save();
}

/**
 * Implements hook_uninstall().
 */
function test_2f72f4a4_uninstall() {
  FieldConfig::loadByName('node', 'page', 'field_lightweight_image')->delete();
  field_purge_batch(10);
}
